<?php $this;  /* @var $this Application_Plugin_Extension_DijitEditor */ ?>
<div class="insetBox">
    <div class="insetBoxT"></div><div class="insetBoxR"></div><div class="insetBoxB"></div><div class="insetBoxL"></div><div class="insetBoxTL"></div><div class="insetBoxTR"></div><div class="insetBoxBL"></div><div class="insetBoxBR"></div>
    <div class="insetBoxBody breadcrumbs">
        <?php
        echo $this->getParam("body");
        ?>
    </div>
</div>