CREATE TABLE Navigation (
id INT UNSIGNED PRIMARY KEY  NOT NULL,
parentId INT UNSIGNED, 
tid INT UNSIGNED NOT NULL,
l INT UNSIGNED NOT NULL,
r INT UNSIGNED NOT NULL,
url VARCHAR(120) NOT NULL DEFAULT "",
`final` MEDIUMTEXT NOT NULL,
`abstract` MEDIUMTEXT NOT NULL,
`plugins` MEDIUMTEXT NOT NULL,
`disabled` TINYINT UNSIGNED NOT NULL DEFAULT 1,
`acl` SMALLINT UNSIGNED NOT NULL DEFAULT 0
) Engine InnoDB;