<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html>
    <head>
        <title>Web-Izgradnja</title>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
            <link rel="stylesheet" href="/templates/webiz/css/reset.css" />
            <link rel="stylesheet" href="/templates/webiz/css/text.css" />
            <link rel="stylesheet" href="/templates/webiz/css/960.css" />
            <link rel="stylesheet" href="/templates/webiz/main.css" />
            
    </head>
    <body>
        <div class="headerBlock"
>            <div class="container_12">
                &nbsp;
            </div>
        </div>
        <div class="menuBlock">
            <div class="container_16">
                <?php
                $menu = $this->navigation()->getRootMenu();
                for($i = 0, $len=sizeof($menu);$i<$len;$i++):
                ?>
                <div class="grid_4">
                    <a href="<?=$menu[$i]['url']?>">
                        <?=$menu[$i]['title']?>
                    </a>
                </div>
                <?php  endfor; ?>
                <div class="clear"></div>
            </div>
        </div>
        <div class="bodyBlock">
            <div class="container_12">
                <div class="grid_3 bodyColHeightFix">
                    <div class="bodyCol">
                        <div class="bodyColHeading">
                            Web stranica za vašu tvrtku
                        </div>
                        <div class="bodyColBody">
                            <br /><br />
                            U potrazi ste za novom stranicom
                            vaše tvrtke, ili samo želite 
                            izvršiti redizajn postojeće. 
                            U mogućnosti smo Vam ponuditi
                            uslugu kompletne izrade Web
                            stranice točno po zadanim 
                            kriterijima.<br /> <br />

                            Cijena izrade osnovne Web 
                            stranice kreće se od 2000kn, u 
                            što je uračnunato 5 stranica i
                            orginalan dizajn stranice.<br /><br />

                            Naravno u cijenu je uračunat i 
                            alat za ažuriranje koji Vam 
                            omogućuje naknadan
                            unos vlastitog sadržaja.
                        </div>
                        <div class="bodyColBottomBorder">

                        </div>
                    </div>
                    
                    
                </div>
                
                <div class="grid_3 bodyColHeightFix">
                    <div class="bodyCol">
                        <div class="bodyColHeading">
                            Web stranica za vašu tvrtku
                        </div>
                        <div class="bodyColBody">
                            <br /><br />
                            U potrazi ste za novom stranicom
                            vaše tvrtke, ili samo želite 
                            izvršiti redizajn postojeće. 
                            U mogućnosti smo Vam ponuditi
                            uslugu kompletne izrade Web
                            stranice točno po zadanim 
                            kriterijima.<br /> <br />

                            Cijena izrade osnovne Web 
                            stranice kreće se od 2000kn, u 
                            što je uračnunato 5 stranica i
                            orginalan dizajn stranice.<br /><br />

                            Naravno u cijenu je uračunat i 
                            alat za ažuriranje koji Vam 
                            omogućuje naknadan
                            unos vlastitog sadržaja.
                        </div>
                        <div class="bodyColBottomBorder">

                        </div>
                    </div>
                    
                    
                </div>
                
                <div class="grid_3 bodyColHeightFix">
                    <div class="bodyCol">
                        <div class="bodyColHeading">
                            Web stranica za vašu tvrtku
                        </div>
                        <div class="bodyColBody">
                            <br /><br />
                            Želite izvršiti određene promjene
                            na postoječoj stranici. Na stranici
                            se nalaze zastarjeli podaci ili vi 
                            želite dodati novu funkciju, npr.:
                            kontakt obrazac, galeriju slika, 
                            katalog proizvoda i sl. <br /><br/>


                            Cijena održavanja statičnih 
                            stranica kreće se od 50kn/kom,
                            dok se cijena održavanja ručno
                            pisanih dinamičnih stranica 
                            kreće od 80kn/kom.

                        </div>
                        <div class="bodyColBottomBorder">

                        </div>
                    </div>
                    
                    
                </div>
                
                <div class="grid_3 bodyColHeightFix">
                    <div class="bodyCol">
                        <div class="bodyColHeading">
                            Web stranica za vašu tvrtku
                        </div>
                        <div class="bodyColBody">
                            <br /><br />
                            U potrazi ste za novom stranicom
                            vaše tvrtke, ili samo želite 
                            izvršiti redizajn postojeće. 
                            U mogućnosti smo Vam ponuditi
                            uslugu kompletne izrade Web
                            stranice točno po zadanim 
                            kriterijima.<br /> <br />

                            Cijena izrade osnovne Web 
                            stranice kreće se od 2000kn, u 
                            što je uračnunato 5 stranica i
                            orginalan dizajn stranice.<br /><br />

                            Naravno u cijenu je uračunat i 
                            alat za ažuriranje koji Vam 
                            omogućuje naknadan
                            unos vlastitog sadržaja.
                        </div>
                        <div class="bodyColBottomBorder">

                        </div>
                    </div>
                    
                    
                </div>
                
                <div class="clear"></div>
            </div>
        </div>
        <div class="bodyBlockFooter">
            <div class="container_12">
                <div class="grid_12"></div>
            </div>
        </div>
        <div class="footerBlock">
            <div class="container_12">
                <div class="grid_12 footerBlockBorder">
                    <div class="grid_3">
                        <h4>Footer 1</h4>
                        <div>
                            Body
                        </div>
                    </div>
                    <div class="grid_4">
                        <h4>Footer 2</h4>
                        <div>
                            Body
                        </div>
                    </div>
                    <div class="grid_4">
                        <h4>Footer 3</h4>
                        <div>
                            Body
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </body>
</html>
