<html>
    <head>
        <title>AZFCMS</title>
    </head>
    <body>
        <div>
            <h3>Glavni menu</h3>
            <ul>
                <?php 
                $tree = $this->navigation->getMenuTree();
                foreach($tree['childNodes'] as $item){
                    ?>
                <li><a href="<?=$item['url']?>"><?=$item['title'] ?></a></li>
                <?php
                }
                ?>
            </ul>
        </div>
        <div>
            <h3>Kontekstualan menu</h3>
            <ul>
                <?php 
                $tree = $this->navigation->getContextMenus();
                foreach($tree['childNodes'] as $item){
                    ?>
                <li><a href="<?=$item['url']?>"><?=$item['title'] ?></a></li>
                <?php
                }
                ?>
            </ul>
        </div>
        
        Another Zend Framework CMS
    </body>
</html>